= cui-parent-pom
:toc: macro
:toclevels: 3
:sectnumlevels: 1

[.discrete]
== Status

image:https://github.com/cuioss/cui-parent-pom/actions/workflows/maven.yml/badge.svg[Java CI with Maven,link=https://github.com/cuioss/cui-parent-pom/actions/workflows/maven.yml]
image:http://img.shields.io/:license-apache-blue.svg[License,link=http://www.apache.org/licenses/LICENSE-2.0.html]
image:https://maven-badges.herokuapp.com/maven-central/de.cuioss/cui-parent-pom/badge.svg[Maven Central,link=https://maven-badges.herokuapp.com/maven-central/de.cuioss/cui-parent-pom]

== What is it?

Parent pom for cui-open-source-projects. It defines and configures a number of maven-plugins, unifying the descendant modules.
It aims at modules being at least Java 17. It defines the sonatype-repositories as read and deploy repositories.

Maven-site result can be found https://cuioss.github.io/cui-parent-pom/[Project-Home-Page]

toc::[]

== Modules

* link:cui-java-bom/README.adoc[cui-java-bom] - Java dependency management
* link:java-ee-bom/README.adoc[java-ee-bom] - Jakarta EE dependency management

== Usage

=== As a parent POM

[source,xml]
----
<parent>
   <groupId>de.cuioss</groupId>
   <artifactId>cui-parent-pom</artifactId>
   <version>${version}</version>
</parent>
----

=== Including dependency management

[source,xml]
----
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>de.cuioss</groupId>
            <artifactId>cui-java-bom</artifactId>
            <version>${version}</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
----

== Usage for Standard java-modules

[source,xml]
----
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>de.cuioss</groupId>
        <artifactId>cui-java-parent</artifactId>
        <version>1.0</version>
    </parent>
    <artifactId>cui-java-sample</artifactId>
    <name>cui java sample</name>
    <packaging>pom</packaging>
    <description>Sample usage of parent-pom</description>
    <dependencies>
        <!-- Provided-->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
        <!-- Unit testing -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
        </dependency>
    </dependencies>
</project>
----

== Updating the Maven Wrapper

To update the Maven Wrapper scripts (mvnw, mvnw.cmd, .mvn/wrapper), run the following command:

[source,shell]
----
./mvnw wrapper:wrapper
----

This will update the Maven Wrapper to the latest version provided by the takari-maven-wrapper-plugin.

== Reproducible Builds

This project implements several measures to ensure reproducible builds. The following practices are already in place:
 
* All plugin and dependency versions are pinned in all pom.xml files. No LATEST, RELEASE, or version ranges are used.
* The Maven Wrapper is present (mvnw, mvnw.cmd, .mvn/wrapper/maven-wrapper.properties) and pins Maven 3.9.6.
* Java version is set explicitly: 
[source,xml]
----
<maven.compiler.source>17</maven.compiler.source> 
<maven.compiler.target>17</maven.compiler.target> 
----
in the root pom.xml, inherited by all modules.
* Reproducibility configuration is set for JAR/WAR plugins in all modules:
 
[source,xml]
----
<configuration>
  <reproducible>true</reproducible>
  <outputTimestamp>2025-04-20T00:00:00Z</outputTimestamp>
</configuration>
----
 
* No non-deterministic resource filtering is used (no timestamp, hostname, or environment injection in resources).
* All GitHub Actions in .github/workflows/ are pinned by commit hash (uses: ...@<commit-sha>).
* The build environment is documented: builds are tested on Linux with Java 17 and Maven 3.9.6 using ./mvnw.
