= java ee-10-bom

Bundles all Jakarta EE 10 related dependencies. This Bill of Materials (BOM) provides managed dependencies for Jakarta EE 10 applications, including JSF components, MicroProfile implementations, and related libraries.

NOTE: This module forward-adopts selected Jakarta EE 11 APIs (web-api `11.0.0`, servlet `6.1.0`) while remaining the "EE 10" baseline for CUI projects.

This module is part of the link:../README.adoc[java-ee-bom] module.

== Usage

To use this BOM in your project, add it to your dependencyManagement section:

[source,xml]
----
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>de.cuioss</groupId>
            <artifactId>java-ee-10-bom</artifactId>
            <version>${version}</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
----

This BOM includes managed dependencies for:

* Jakarta EE 10 Web API
* MyFaces JSF Implementation
* OmniFaces
* PrimeFaces
* Weld (CDI Implementation)
* MicroProfile APIs and implementations
* RESTEasy
* Parsson (Jakarta JSON implementation)

Quarkus dependencies are managed separately in the link:quarkus-bom/README.adoc[quarkus-bom] submodule.
