name: Maven Release

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    name: release

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: sonatype-nexus-snapshots
        server-username: MAVEN_USERNAME
        server-password: MAVEN_CENTRAL_TOKEN
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
        cache: maven

    - name: Configure Git author
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Cuioss Robot Action"

    - name: Maven release current snapshot
      run: |
        mvn -Prelease-pom -B release:clean release:prepare
        mvn -Prelease-pom -B release:perform -DskipTests
      env:
        MAVEN_USERNAME: ${{ secrets.OSS_SONATYPE_USERNAME }}
        MAVEN_CENTRAL_TOKEN: ${{ secrets.OSS_SONATYPE_PASSWORD }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

